apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    app: python-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: ganesh823/python-flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

