apiVersion: v1
kind: Service
metadata:
  name: python-flask-app
spec:
  selector:
    app: python-flask-app
  ports:
    - protocol: TCP
      port: 80           # Internal port for the service
      targetPort: 5000    # Port on the container where the app listens
      nodePort: 31749     # External NodePort for accessing the service
  type: NodePort

