apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-water-gun-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-water-gun-game
  template:
    metadata:
      labels:
        app: snake-water-gun-game
    spec:
      containers:
      - name: snake-water-gun-game
        image: ganesh823/snake-water-gun-game  # The name of the image you built in Minikube
        ports:
        - containerPort: 8000  # The port Flask runs on in your Dockerfile
